stages:
  - test
  - build

test project:
  stage: test
  image: node
  script:
    - npm install
    - npm test

build project:
  stage: build
  image: node
  script:
    - npm install
    - npm run build
